version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - '3000:3000'
    container_name: mode-server
    volumes:
      - /usr/src/app/node_modules
      - ./server/db:/usr/src/app/db

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - '4000:4000'
    container_name: mode-client
    stdin_open: true
    volumes:
      - /usr/src/app/node_modules
