version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    container_name: modo-server
    volumes:
      - ./server:usr/src/monorepo/server
      - /usr/src/monorepo/node_modules
  
  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_API_URL: "http://modo-server:3000"
    ports:
      - "4000:4000"
    container_name: modo-client
    stdin_open: true
    volumes:
      - ./client:usr/src/monorepo/client
      - /usr/src/monorepo/node_modules
    environment: 
      NEXT_PUBLIC_API_URL: "http://modo-server:3000"
